# Generated by Django 3.1.5 on 2022-05-15 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0030_auto_20220515_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 5, 16, 9, 613516)),
        ),
    ]
