# Generated by Django 3.1.5 on 2022-08-21 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0031_auto_20220515_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 3, 35, 43, 365159)),
        ),
    ]
